 ### pandas

 >pandas is a powerfull python library for manipulation and analysis of data

 >its a open source library

 >fast(built on top of numpy) , flexible(different resource), productive library

#### Install

In [11]:
 pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd

In [13]:
pd.__version__

'2.2.3'

#### Series - one dimensional array (data structure)with label

In [14]:
l1 = [1,2,3,4,5]
type(l1)

list

In [15]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
pd.Series(l1, index=["a","b","c","d","e"], name ="my series")

a    1
b    2
c    3
d    4
e    5
Name: my series, dtype: int64

In [17]:
s=pd.Series(l1, index=["a","b","c","d","e"], name ="my series")

In [18]:
s

a    1
b    2
c    3
d    4
e    5
Name: my series, dtype: int64

In [19]:
s['a']

np.int64(1)

In [20]:
type(s)

pandas.core.series.Series

In [21]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [22]:
s.values

array([1, 2, 3, 4, 5])

Note : index in series are immutable(cant change)

In [23]:
s.index[0] = 'z'

TypeError: Index does not support mutable operations

In [ ]:
# changing the index of pandas series

s.rename(index={'b':'y'},inplace=True)

In [ ]:
s

a    1
y    2
c    3
d    4
e    5
Name: my series, dtype: int64

### DataFrame - its a 2d array (just like tables)

rows and cols

In [ ]:
dict1={'Name':['virat','rohit','dhoni','jadeja','bumrah','virat'] ,
        'age':[34,33,40,32,30,28] ,
        'Marks':[85,90,75,80,70,80] ,
        'role':['Batsman','Batsman','Wicket keeper','All rounder','Bowler','bowler']
        }

df=pd.DataFrame(dict1)

In [ ]:
df

     Name  age  Marks           role
0   virat   34     85        Batsman
1   rohit   33     90        Batsman
2   dhoni   40     75  Wicket keeper
3  jadeja   32     80    All rounder
4  bumrah   30     70         Bowler
5   Shami   28     80         bowler

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head

<bound method NDFrame.head of      Name  age  Marks           role
0   virat   34     85        Batsman
1   rohit   33     90        Batsman
2   dhoni   40     75  Wicket keeper
3  jadeja   32     80    All rounder
4  bumrah   30     70         Bowler
5   Shami   28     80         bowler>

In [ ]:
df.tail

<bound method NDFrame.tail of      Name  age  Marks           role
0   virat   34     85        Batsman
1   rohit   33     90        Batsman
2   dhoni   40     75  Wicket keeper
3  jadeja   32     80    All rounder
4  bumrah   30     70         Bowler
5   Shami   28     80         bowler>

In [ ]:
len(df)

6

In [ ]:
df.count()

Name     6
age      6
Marks    6
role     6
dtype: int64

In [ ]:
df.columns

Index(['Name', 'age', 'Marks', 'role'], dtype='object')

In [ ]:
df['Name']

0     virat
1     rohit
2     dhoni
3    jadeja
4    bumrah
5     Shami
Name: Name, dtype: object

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df['Name'].value_counts()

Name
virat     2
rohit     1
dhoni     1
jadeja    1
bumrah    1
Name: count, dtype: int64

In [ ]:
df=pd.DataFrame(dict1)
df

     Name  age  Marks           role
0   virat   34     85        Batsman
1   rohit   33     90        Batsman
2   dhoni   40     75  Wicket keeper
3  jadeja   32     80    All rounder
4  bumrah   30     70         Bowler
5   virat   28     80         bowler

In [ ]:
df.size

24

##basic opretions

>improting data set from different files 

>importing tabular data set

In [25]:
import pandas as pd

In [29]:
df=pd.read_csv(r"C:\Users\klemp\Desktop\DataAnalyst(nisha)\data set\ETH_1h.csv")

In [34]:
df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [32]:
stock_df=pd.read_csv(r"C:\Users\klemp\Desktop\DataAnalyst(nisha)\data set\ETH_1h.csv")

In [33]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

by defuault head()will return first five rows

In [36]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

head(10)it will return first ten rows

In [37]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

bottom five rows

In [38]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

len is used to get number of rows

In [39]:
len(stock_df)

23674

Accss columns name of dataframe

In [41]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [46]:
##accessing a column in a Datasframe

stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [47]:
##accessing a column in a Datasframe

stock_df[['Open','Close']]

         Open   Close
0      129.94  128.71
1      119.51  129.94
2      124.47  119.51
3      124.08  124.47
4      124.85  124.08
...       ...     ...
23669  265.74  272.57
23670  268.79  265.74
23671  274.83  268.79
23672  275.01  274.83
23673  279.98  275.01

[23674 rows x 2 columns]

In [48]:
##accssing multiple  columns use array
stock_df[['Open','Symbol','High']]

         Open  Symbol    High
0      129.94  ETHUSD  131.82
1      119.51  ETHUSD  132.02
2      124.47  ETHUSD  124.85
3      124.08  ETHUSD  127.42
4      124.85  ETHUSD  129.51
...       ...     ...     ...
23669  265.74  ETHUSD  272.74
23670  268.79  ETHUSD  269.90
23671  274.83  ETHUSD  274.93
23672  275.01  ETHUSD  275.01
23673  279.98  ETHUSD  279.99

[23674 rows x 3 columns]

indexing loc

In [51]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [52]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

loc-lable location

In [ ]:
df.loc[23567]

Date      2017-07-05 09-PM
Symbol              ETHUSD
Open                 265.2
High                268.27
Low                  263.4
Close               267.99
Volume          1373223.25
Name: 23567, dtype: object

In [87]:
df.loc[23567,Close:Open]]

SyntaxError: unmatched ']' (1871893914.py, line 1)

In [53]:
df.loc[1]

Date      2020-03-13 07-PM
Symbol              ETHUSD
Open                119.51
High                132.02
Low                  117.1
Close               129.94
Volume          7579741.09
Name: 1, dtype: object

In [55]:
stock_df.iloc[5]

Date      2020-03-13 03-PM
Symbol              ETHUSD
Open                128.39
High                 128.9
Low                 116.06
Close               124.85
Volume           7378976.0
Name: 5, dtype: object

In [62]:
stock_df.loc[0:10,['Date','High','Open','Symbol']]

                Date    High    Open  Symbol
0   2020-03-13 08-PM  131.82  129.94  ETHUSD
1   2020-03-13 07-PM  132.02  119.51  ETHUSD
2   2020-03-13 06-PM  124.85  124.47  ETHUSD
3   2020-03-13 05-PM  127.42  124.08  ETHUSD
4   2020-03-13 04-PM  129.51  124.85  ETHUSD
5   2020-03-13 03-PM  128.90  128.39  ETHUSD
6   2020-03-13 02-PM  137.90  134.03  ETHUSD
7   2020-03-13 01-PM  140.95  131.35  ETHUSD
8   2020-03-13 12-PM  134.60  128.93  ETHUSD
9   2020-03-13 11-AM  133.17  132.60  ETHUSD
10  2020-03-13 10-AM  134.99  133.80  ETHUSD

In [63]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [66]:
l=[1,2,3,4,5]
l[1:4] #slicing a list

[2, 3, 4]

In [74]:
d2=[[1,2,3],
    [4,5,6],
    [7,8,9]]
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [71]:
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Slicing in loc(labaled location)

In [77]:
stock_df.loc[10,'Date':'High']

Date      2020-03-13 10-AM
Symbol              ETHUSD
Open                 133.8
High                134.99
Name: 10, dtype: object

### iloc - index based location,when we dont konw lables for row and colmns

In [81]:
stock_df.iloc

In [83]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [84]:
stock_df.iloc[2:2]

Empty DataFrame
Columns: [Date, Symbol, Open, High, Low, Close, Volume]
Index: []

In [90]:
stock_df.iloc[2,2]

np.float64(124.47)

In [91]:
stock_df.iloc[2,2:5] #multiple siciling

Open    124.47
High    124.85
Low      115.5
Name: 2, dtype: object

In [89]:
stock_df.iloc[3,[2,4]]

Open    124.08
Low     121.63
Name: 3, dtype: object

In [92]:
stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

In [95]:
stock_df['High']>100

0        True
1        True
2        True
3        True
4        True
         ...
23669    True
23670    True
23671    True
23672    True
23673    True
Name: High, Length: 23674, dtype: bool

In [99]:
f1=stock_df['High']>100

stock_df[f1]

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23375 rows x 7 columns]

In [101]:
stock_gt_130=stock_df

In [102]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [105]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [104]:
stock_gt_130.reset_index(drop=True)

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [107]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [110]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Open                279.98
High                279.99
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [106]:
len(stock_df)

23674

In [111]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [112]:
stock_df['Random_col'] =range(1,len(stock_df)+1)

dropping coloum

In [113]:
stock_df.drop(columns=['Random_col'])

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [114]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [115]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [119]:
stock_df.drop(columns=['Open','High'],inplace=True)

In [120]:
stock_df.drop(23456,axis=0,inplace=True)

Dropping row